root: true
extends: "@hkh12"
plugins:
  - svelte3
env:
  browser: true
  node: true
  es6: true
overrides:
  - files:
      - config/*
      - docs/*
    rules:
      import/no-extraneous-dependencies: off
